version: "3.8"

services:
  django:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env

  pytest:
    build: .
    container_name: pytest-app
    command: pytest -rP
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
